name: Auto Merge To Develop

on:
  push:
    branches:
      - '**'
      - '!develop'

permissions:
  contents: write

jobs:
  merge-to-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get source branch
        run: |
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Merge into develop
        run: |
          git fetch origin

          git checkout develop
          git pull origin develop

          git merge origin/${SOURCE_BRANCH} --no-edit

          git push origin develop
