name: Auto Merge To Develop

on:
  push:
    branches:
      - '**'
      - '!develop'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  merge-to-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Merge into develop
        run: |
          SOURCE_BRANCH=${GITHUB_REF#refs/heads/}

          git fetch origin
          git checkout develop
          git pull origin develop

          git merge origin/$SOURCE_BRANCH --no-edit
          git push origin develop
